/*
CREATE TABLE 테이블이름(
    컬럼이름    자료형(크기),
    컬럼이름    자료형(크기),
    컬럼이름    자료형(크기)
)
*/
DROP TABLE EXPERT_TBL;

CREATE TABLE EXPERT_TBL(
    MEMBER_CODE NUMBER PRIMARY KEY,
    MEMBER_ID   VARCHAR2(20) UNIQUE,
    MEMBER_PW   VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(10) NOT NULL,
    MEMBER_ADDR VARCHAR2(50) NOT NULL,
    GENDER      CHAR(3) CHECK(GENDER IN('남','여')),
    PHONE       CHAR(13) DEFAULT '010-0000-0000'
);
COMMENT ON COLUMN EXPERT_TBL.MEMBER_CODE IS '회원전용코드';
COMMENT ON COLUMN EXPERT_TBL.MEMBER_ID IS '회원아이디';
COMMENT ON COLUMN EXPERT_TBL.MEMBER_PW IS '회원비밀번호';
COMMENT ON COLUMN EXPERT_TBL.MEMBER_NAME IS '회원이름';
COMMENT ON COLUMN EXPERT_TBL.MEMBER_ADDR IS '회원거주지';
COMMENT ON COLUMN EXPERT_TBL.GENDER IS '회원성별';
COMMENT ON COLUMN EXPERT_TBL.PHONE IS '회원전화번호';

CREATE TABLE COMPANY_TBL(
    MEMBER_CODE NUMBER REFERENCES EXPERT_TBL ON DELETE CASCADE,
    SKILL       VARCHAR2(50)
);
COMMENT ON COLUMN COMPANY_TBL.MEMBER_CODE IS '회원전용코드';
COMMENT ON COLUMN COMPANY_TBL.SKILL IS '회원능력';

INSERT INTO EXPERT_TBL VALUES(1,'USER01','1111','부가원','서울 마포구','여','010-2051-5290');
INSERT INTO EXPERT_TBL VALUES(2,'USER02','2222','루이','서울 마포구','남','010-2222-2222');
INSERT INTO EXPERT_TBL VALUES(3,'USER03','3333','밤','경기 군포시','여',DEFAULT);
INSERT INTO EXPERT_TBL VALUES(4,'USER04','4444','김덕팔','충북 청주시','남','010-4444-4444');
INSERT INTO EXPERT_TBL VALUES(5,NULL,'5555','손용석','경기 군포시','남','010-5555-5555');
INSERT INTO EXPERT_TBL(MEMBER_CODE,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_ADDR,GENDER)
            VALUES(6,'user06','6666','박수박','서울 강서구','여');

DELETE FROM EXPERT_TBL WHERE MEMBER_CODE = 4;
DELETE FROM EXPERT_TBL;
SELECT * FROM EXPERT_TBL;

INSERT INTO COMPANY_TBL VALUES(1,'하품하기');
INSERT INTO COMPANY_TBL VALUES(2,'잠자기');
INSERT INTO COMPANY_TBL VALUES(3,'고함지르기');
INSERT INTO COMPANY_TBL VALUES(4,'뒷구르기');
INSERT INTO COMPANY_TBL VALUES(5,'앞구르기');
INSERT INTO COMPANY_TBL VALUES(NULL,'옆구르기');
INSERT INTO COMPANY_TBL VALUES(6,NULL);

DELETE FROM COMPANY_TBL WHERE MEMBER_CODE IS NULL;
DELETE FROM COMPANY_TBL WHERE MEMBER_CODE = 4;
DROP TABLE COMPANY_TBL;

SELECT * FROM COMPANY_TBL;