CREATE TABLE EXAM_MEMBER(
    MEMBER_NO   NUMBER          PRIMARY KEY,
    MEMBER_ID   VARCHAR2(20)    UNIQUE NOT NULL,
    MEMBER_PW   VARCHAR2(30)    NOT NULL,
    MEMBER_NAME VARCHAR2(20)    NOT NULL,
    MEMBER_PHONE    CHAR(11)
);

CREATE TABLE EXAM_BOARD(
    BOARD_NO        NUMBER          PRIMARY KEY,
    BOARD_TITLE     VARCHAR2(100)   NOT NULL,
    BOARD_CONTENT   VARCHAR2(2000)  NOT NULL,
    BOARD_WRITER    NUMBER REFERENCES EXAM_MEMBER ON DELETE SET NULL,
    READ_COUNT      NUMBER,
    WRITE_DATE      DATE
);

CREATE SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE BOARD_SEQ;

DROP TABLE EXAM_MEMBER;
DROP TABLE EXAM_BOARD;
DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE BOARD_SEQ;

INSERT INTO EXAM_MEMBER VALUES(MEMBER_SEQ.NEXTVAL, 'user01', '1111', '유저1', '01012341234');
INSERT INTO EXAM_BOARD VALUES(BOARD_SEQ.NEXTVAL, '제목', '내용', 1, 0, SYSDATE);

SELECT * FROM EXAM_MEMBER;
SELECT * FROM EXAM_BOARD;
