-- 회원 테이블 작성
CREATE TABLE MEMBER(
    MEMBER_NO   NUMBER PRIMARY KEY,
    MEMBER_USERID   VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_USERPWD  CHAR(20) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_GENDER   VARCHAR2(3) CHECK(MEMBER_GENDER IN('남','여')),
    MEMBER_EMAIL    VARCHAR2(30) NOT NULL
);

-- 회원 고유번호 자동 생성기 작성(1000번부터 1씩 증가, 최대 100만)
CREATE SEQUENCE MEMBER_NO_SEQ
START WITH 1000
INCREMENT BY 1
MAXVALUE 1000000
NOCYCLE
NOCACHE;

-- 게시판 테이블 작성
CREATE TABLE BOARD(
    BOARD_NO    NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(20) NOT NULL,
    BOARD_CONTENT   VARCHAR2(200) NOT NULL,
    BOARD_WRITEDATE DATE NOT NULL,
    BOARD_NICKNAME  VARCHAR2(20) REFERENCES MEMBER(MEMBER_NICKNAME)ON DELETE SET NULL NOT NULL
);
ALTER TABLE BOARD
MODIFY BOARD_NICKNAME NULL;

DELETE FROM MEMBER WHERE MEMBER_NO = 1002;

-- 게시판 글 번호 자동 생성기 작성(1번부터 1씩 증가, 최대 500만)
CREATE SEQUENCE BOARD_NO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 5000000
NOCYCLE
NOCACHE;

-- 회원번호 , 회원닉네임, 회원 이메일, 회원 작성글 제목을 볼 수 있는 VIEW 생성
CREATE OR REPLACE VIEW MEMBER_VIEW
AS
SELECT MEMBER_NO, MEMBER_NICKNAME, MEMBER_EMAIL, BOARD_TITLE
FROM MEMBER
JOIN BOARD ON (MEMBER_NICKNAME=BOARD_NICKNAME);
SELECT * FROM MEMBER_VIEW;

-- MEMBER와 BOARD 테이블을 'M' 과 'B' 로도 검색 할 수 있게 만들기(비공개동의어로 생성)
CREATE SYNONYM M FOR MEMBER;
SELECT * FROM M;
CREATE SYNONYM B FOR MEMBER;
SELECT * FROM B;

-- 회원 정보 INSERT, UPDATE
INSERT INTO MEMBER VALUES(MEMBER_NO_SEQ.NEXTVAL, 'user03', '33333', '부가원', '여', 'bkw1104@naver.com');
UPDATE MEMBER SET MEMBER_NO = 1002 WHERE MEMBER_USERID = 'user03';
SELECT * FROM MEMBER;

-- 회원 게시글 INSERT, UPDATE, DELETE
INSERT INTO BOARD VALUES(BOARD_NO_SEQ.NEXTVAL, '저는요', '집에 가고싶습니다.', SYSDATE, '부가원');
UPDATE BOARD SET BOARD_NO = 3 WHERE BOARD_NICKNAME = '부가원';
DELETE FROM BOARD WHERE BOARD_NO = 3;
SELECT * FROM BOARD;

-- ~ 2022-07-26 시험 범위! (OBJECT 까지!)






































