--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."NOTICE" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(300 BYTE), 
	"NOTICE_WRITER" VARCHAR2(20 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(4000 BYTE), 
	"READ_COUNT" NUMBER, 
	"REG_DATE" CHAR(10 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILEPATH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WEBSERVER.NOTICE
SET DEFINE OFF;
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (1,'공지사항1','user01','공지사항내용1',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (2,'공지사항2','user01','공지사항내용2',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (3,'공지사항3','user01','공지사항내용3',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (4,'공지사항4','user01','공지사항내용4',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (5,'공지사항5','user01','공지사항내용5',7,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (6,'공지사항6','user01','공지사항내용6',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (7,'공지사항7','user01','공지사항내용7',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (8,'공지사항8','user01','공지사항내용8',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (9,'공지사항9','user01','공지사항내용9',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (10,'공지사항10','user01','공지사항내용10',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (11,'공지사항11','user01','공지사항내용11',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (12,'공지사항12','user01','공지사항내용12',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (13,'공지사항13','user01','공지사항내용13',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (14,'공지사항14','user01','공지사항내용14',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (15,'공지사항15','user01','공지사항내용15',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (16,'공지사항16','user01','공지사항내용16',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (17,'공지사항17','user01','공지사항내용17',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (18,'공지사항18','user01','공지사항내용18',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (19,'공지사항19','user01','공지사항내용19',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (20,'공지사항20','user01','공지사항내용20',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (21,'공지사항21','user01','공지사항내용21',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (22,'공지사항22','user01','공지사항내용22',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (23,'공지사항23','user01','공지사항내용23',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (24,'공지사항24','user01','공지사항내용24',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (25,'공지사항25','user01','공지사항내용25',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (26,'공지사항26','user01','공지사항내용26',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (27,'공지사항27','user01','공지사항내용27',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (28,'공지사항28','user01','공지사항내용28',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (29,'공지사항29','user01','공지사항내용29',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (30,'공지사항30','user01','공지사항내용30',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (31,'공지사항31','user01','공지사항내용31',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (32,'공지사항32','user01','공지사항내용32',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (33,'공지사항33','user01','공지사항내용33',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (34,'공지사항34','user01','공지사항내용34',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (35,'공지사항35','user01','공지사항내용35',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (36,'공지사항36','user01','공지사항내용36',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (37,'공지사항37','user01','공지사항내용37',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (38,'공지사항38','user01','공지사항내용38',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (39,'공지사항39','user01','공지사항내용39',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (40,'공지사항40','user01','공지사항내용40',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (41,'공지사항41','user01','공지사항내용41',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (42,'공지사항42','user01','공지사항내용42',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (43,'공지사항43','user01','공지사항내용43',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (44,'공지사항44','user01','공지사항내용44',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (45,'공지사항45','user01','공지사항내용45',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (46,'공지사항46','user01','공지사항내용46',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (47,'공지사항47','user01','공지사항내용47',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (48,'공지사항48','user01','공지사항내용48',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (49,'공지사항49','user01','공지사항내용49',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (50,'공지사항50','user01','공지사항내용50',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (51,'공지사항51','user01','공지사항내용51',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (52,'공지사항52','user01','공지사항내용52',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (53,'공지사항53','user01','공지사항내용53',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (54,'공지사항54','user01','공지사항내용54',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (55,'공지사항55','user01','공지사항내용55',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (56,'공지사항56','user01','공지사항내용56',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (57,'공지사항57','user01','공지사항내용57',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (58,'공지사항58','user01','공지사항내용58',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (59,'공지사항59','user01','공지사항내용59',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (60,'공지사항60','user01','공지사항내용60',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (61,'공지사항61','user01','공지사항내용61',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (62,'공지사항62','user01','공지사항내용62',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (63,'공지사항63','user01','공지사항내용63',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (64,'공지사항64','user01','공지사항내용64',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (65,'공지사항65','user01','공지사항내용65',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (66,'공지사항66','user01','공지사항내용66',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (67,'공지사항67','user01','공지사항내용67',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (68,'공지사항68','user01','공지사항내용68',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (69,'공지사항69','user01','공지사항내용69',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (70,'공지사항70','user01','공지사항내용70',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (71,'공지사항71','user01','공지사항내용71',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (72,'공지사항72','user01','공지사항내용72',1,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (73,'공지사항73','user01','공지사항내용73',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (74,'공지사항74','user01','공지사항내용74',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (75,'공지사항75','user01','공지사항내용75',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (76,'공지사항76','user01','공지사항내용76',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (77,'공지사항77','user01','공지사항내용77',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (78,'공지사항78','user01','공지사항내용78',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (79,'공지사항79','user01','공지사항내용79',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (80,'공지사항80','user01','공지사항내용80',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (81,'공지사항81','user01','공지사항내용81',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (82,'공지사항82','user01','공지사항내용82',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (83,'공지사항83','user01','공지사항내용83',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (84,'공지사항84','user01','공지사항내용84',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (85,'공지사항85','user01','공지사항내용85',0,'2022-09-01',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (86,'공지사항86','user01','공지사항내용86',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (87,'공지사항87','user01','공지사항내용87',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (88,'공지사항88','user01','공지사항내용88',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (89,'공지사항89','user01','공지사항내용89',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (90,'공지사항90','user01','공지사항내용90',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (91,'공지사항91','user01','공지사항내용91',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (92,'공지사항92','user01','공지사항내용92',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (93,'공지사항93','user01','공지사항내용93',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (94,'공지사항94','user01','공지사항내용94',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (95,'공지사항95','user01','공지사항내용95',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (96,'공지사항96','user01','공지사항내용96',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (97,'공지사항97','user01','공지사항내용97',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (98,'공지사항98','user01','공지사항내용98',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (99,'공지사항99','user01','공지사항내용99',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (100,'공지사항100','user01','공지사항내용100',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (101,'공지사항101','user01','공지사항내용101',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (102,'공지사항102','user01','공지사항내용102',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (103,'공지사항103','user01','공지사항내용103',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (104,'공지사항104','user01','공지사항내용104',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (105,'공지사항105','user01','공지사항내용105',0,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (106,'공지사항106','user01','공지사항내용106',1,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (107,'공지사항107','user01','공지사항내용107',1,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (108,'공지사항108','user01','공지사항내용108',2,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (109,'공지사항109','user01','공지사항내용109',59,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (110,'공지사항110','user01','공지사항내용110',1,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (111,'공지사항111','user01','공지사항내용111',3,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (112,'공지사항112','user01','공지사항내용112',6,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (119,'오라클의 외마디...','user04','첨부파일을 확인하세요.',49,'2022-09-02','오라클의비명.PNG','오라클의비명3.PNG');
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (114,'첨부파일이 있는 글입니다.','user01','뻥이야~

~~

~(^.^)~',45,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (120,'첨부파일이 있는 글입니다.','user04','~!!!!!!!
~진짜~
!있음!~
!!!!!!!~',37,'2022-09-02','0810웹사이트구현.txt','0810웹사이트구현.txt');
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (121,'첨부파일이 있는 글입니다.','user01','있었는데요.

없었습니다.',63,'2022-09-02',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (122,'집가서','user04','빨래하기',118,'2022-09-02','04_MVC 아키텍처.pdf','04_MVC 아키텍처.pdf');
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (123,'????????????????????','user01','????????????????????',3,'2022-09-07',null,null);
Insert into WEBSERVER.NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_WRITER,NOTICE_CONTENT,READ_COUNT,REG_DATE,FILENAME,FILEPATH) values (125,'빙글빙글','user01','<p style="text-align: center; "><img src="/upload/editor/drug.jpg" style="width: 500px;"></p><p style="text-align: center; ">돌아가는 밤이의 하루</p>',7,'2022-09-07',null,null);
--------------------------------------------------------
--  DDL for Index SYS_C007223
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBSERVER"."SYS_C007223" ON "WEBSERVER"."NOTICE" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."NOTICE" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."NOTICE" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."NOTICE" MODIFY ("NOTICE_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."NOTICE" ADD FOREIGN KEY ("NOTICE_WRITER")
	  REFERENCES "WEBSERVER"."MEMBER_TBL" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
