--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."MEMBER_TBL" 
   (	"MEMBER_NO" NUMBER, 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(20 BYTE), 
	"MEMBER_NAME" VARCHAR2(21 BYTE), 
	"MEMBER_PHONE" CHAR(13 BYTE), 
	"MEMBER_ADDR" VARCHAR2(100 BYTE), 
	"MEMBER_LEVEL" NUMBER, 
	"ENROLL_DATE" CHAR(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WEBSERVER.MEMBER_TBL
SET DEFINE OFF;
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (1,'user01','1104','유저1','010-1111-1111','경기도',1,'2022-08-30');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (2,'user02','2222','유저2','010-2222-2222','부산 기장군',2,'2022-08-30');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (3,'user03','3333','유저3','010-3333-3333','서울시',3,'2022-08-30');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (4,'user04','1104','유저4','010-4444-4444','대전',1,'2022-08-30');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (5,'user05','5555','유저5','010-5555-5555','광주',2,'2022-08-30');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (6,'user06','6666','유저6','010-6666-6666','제주',3,'2022-08-30');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (7,'zoo','123555','현주','010-9022-7417','부천',2,'2022-09-01');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (8,'만두맨','1234','만두맨','1234         ','누구세요???????????',2,'2022-09-05');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (9,'sweetgirl','1234','스윗걸','010-7501-3006','내마음속',2,'2022-09-06');
Insert into WEBSERVER.MEMBER_TBL (MEMBER_NO,MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_PHONE,MEMBER_ADDR,MEMBER_LEVEL,ENROLL_DATE) values (10,'user07','7777','유저7','010-7777-7777','여수시',2,'2022-09-06');
--------------------------------------------------------
--  DDL for Index SYS_C007219
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBSERVER"."SYS_C007219" ON "WEBSERVER"."MEMBER_TBL" ("MEMBER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007220
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBSERVER"."SYS_C007220" ON "WEBSERVER"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."MEMBER_TBL" ADD UNIQUE ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."MEMBER_TBL" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
