--------------------------------------------------------
--  ÆÄÀÏÀÌ »ý¼ºµÊ - ¼ö¿äÀÏ-9¿ù-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NOTICE_COMMENT
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."NOTICE_COMMENT" 
   (	"NC_NO" NUMBER, 
	"NC_WRITER" VARCHAR2(20 BYTE), 
	"NC_CONTENT" VARCHAR2(1000 BYTE), 
	"NC_DATE" CHAR(10 BYTE), 
	"NOTICE_REF" NUMBER, 
	"NC_REF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WEBSERVER.NOTICE_COMMENT
SET DEFINE OFF;
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (19,'user01','¿ì¿Í..','2022-09-05',122,5);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (2,'user02','¤¡-','2022-09-05',121,null);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (4,'user05','~(¤¡- )~','2022-09-05',114,null);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (5,'user05','@}-----------','2022-09-05',122,null);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (10,'user04','¤¡-','2022-09-05',121,2);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (12,'user01','´ñ±Û........','2022-09-05',109,null);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (13,'user01','´ë´ñ±Û.','2022-09-05',109,12);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (14,'user01','´ë´ñ±Û..','2022-09-05',109,12);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (15,'user01','´ë´ë´ñ±Û...','2022-09-05',109,12);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (16,'user01','´ñ±Û.','2022-09-05',109,null);
Insert into WEBSERVER.NOTICE_COMMENT (NC_NO,NC_WRITER,NC_CONTENT,NC_DATE,NOTICE_REF,NC_REF) values (17,'user01','¤¡-','2022-09-05',121,2);
--------------------------------------------------------
--  DDL for Index SYS_C007226
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBSERVER"."SYS_C007226" ON "WEBSERVER"."NOTICE_COMMENT" ("NC_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table NOTICE_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" ADD PRIMARY KEY ("NC_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" MODIFY ("NC_CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NOTICE_COMMENT
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" ADD FOREIGN KEY ("NC_WRITER")
	  REFERENCES "WEBSERVER"."MEMBER_TBL" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" ADD FOREIGN KEY ("NOTICE_REF")
	  REFERENCES "WEBSERVER"."NOTICE" ("NOTICE_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WEBSERVER"."NOTICE_COMMENT" ADD FOREIGN KEY ("NC_REF")
	  REFERENCES "WEBSERVER"."NOTICE_COMMENT" ("NC_NO") ON DELETE CASCADE ENABLE;
