--------------------------------------------------------
--  파일이 생성됨 - 수요일-9월-14-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PHOTO
--------------------------------------------------------

  CREATE TABLE "WEBSERVER"."PHOTO" 
   (	"PHOTO_NO" NUMBER, 
	"PHOTO_WRITER" VARCHAR2(20 BYTE), 
	"PHOTO_TITLE" VARCHAR2(100 BYTE), 
	"PHOTO_CONTENT" VARCHAR2(1000 BYTE), 
	"FILEPATH" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WEBSERVER.PHOTO
SET DEFINE OFF;
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (3,'user01','성당','당다라당당','church.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (4,'user01','국가에서 허락한','유일한 마약','drug.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (1,'user01','벚꽃','그렇다','blossom.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (2,'user01','크리스마스','산타모자','christmas.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (5,'user01','발자국','이럴 때가 있었지','gamsung.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (6,'user01','멀리서 느껴지는 시선','부담스럽다','help.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (7,'user01','축제였다.','이럴 때가 있었지','hosu.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (8,'user01','솜뭉치','솜방망이','iloveher.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (9,'user01','자리 뺏김','동글동글이','morunungoyangyi.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (10,'user01','왁','왁왁','mybaby.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (11,'user01','창덕궁','이었따','palace2.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (12,'user01','공주','바보','princess.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (14,'user01','바다','바다닥','sea1.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (15,'user01','가을','여름 좋았는데','seefall.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (16,'user01','인생샷','갈매기의','shirimpggang.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (17,'user01','mybaby','mysweetlittlekitty','sweetlittlekitty.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (18,'user01','들여다보지마세요','뭅니다','thatsmygirl.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (19,'user01','윤슬','그렇읍니다.','uzzultv.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (26,'sweetgirl','지금 열심히 수정중이에여...뚝딱뚝딱ㅜ','저를 채찍질하시네여..ㅜㅋㅋㅋㅋㅋㅋ','화면 캡처 2022-09-07 143120.png');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (23,'user01','야채','채소','yachae.jpg');
Insert into WEBSERVER.PHOTO (PHOTO_NO,PHOTO_WRITER,PHOTO_TITLE,PHOTO_CONTENT,FILEPATH) values (25,'sweetgirl','왔다가여~','v^^v','조정석v1.png');
--------------------------------------------------------
--  DDL for Index SYS_C007235
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBSERVER"."SYS_C007235" ON "WEBSERVER"."PHOTO" ("PHOTO_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."PHOTO" ADD PRIMARY KEY ("PHOTO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WEBSERVER"."PHOTO" MODIFY ("PHOTO_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBSERVER"."PHOTO" MODIFY ("PHOTO_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PHOTO
--------------------------------------------------------

  ALTER TABLE "WEBSERVER"."PHOTO" ADD FOREIGN KEY ("PHOTO_WRITER")
	  REFERENCES "WEBSERVER"."MEMBER_TBL" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
